import { build } from 'esbuild';
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const root = new URL('../', import.meta.url);
await build({
	absWorkingDir: fileURLToPath(root),
	entryPoints: ['src/client/markdown.js'],
	outfile: 'public/markdown.js',
	bundle: true,
	format: 'esm',
	platform: 'browser',
	target: 'es2022',
	minify: true,
	legalComments: 'eof',
	banner: { js: '// Generated by npm run build:client. See markdown.LICENSE.txt for dependency licenses.' },
});

const licenses = await Promise.all(['marked', 'dompurify'].map(async (name) => {
	const license = await readFile(new URL(`node_modules/${name}/LICENSE`, root), 'utf8');
	return `${name}\n${'='.repeat(name.length)}\n${license}`;
}));
await writeFile(new URL('public/markdown.LICENSE.txt', root), licenses.join('\n\n'));
